name: Deploy
description: Deploy serverless application
inputs:
  branch:
    description: "A branch passed from the caller workflow"
    required: true
    type: string
  environment:
    description: "An environment passed from the caller workflow"
    required: true
    type: string
  aws_artifacts_bucket:
    description: S3 artifacts bucket name
    required: true
    type: string
  aws_region:
    description: AWS region
    required: true
    type: string
  map_api_key:
    description: Map API key
    required: true
    type: string

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pipenv
      run: python -m pip install --upgrade pip wheel pipenv
    - uses: actions/setup-node@v2
      with:
        node-version: 17
    - run: npm ci
    - name: Install Serveless
      run: npm install -g serverless
    - name: Deploy
      run: serverless deploy --stage ${{ inputs.environment}}-${{ inputs.branch }}
      env:
        AWS_REGION: ${{ inputs.aws_region }}
        AWS_CLOSESTWINS_ARTIFACTS_BUCKET: ${{ inputs.aws_artifacts_bucket }}
        SHARED_API_BRANCH: master
        ENVIRONMENT: ${{ inputs.environment}}
        MAP_API_KEY: ${{ inputs.map_api_key }}