name: Deploy master stack
on:
  push:
    branches:
      - master

jobs:
  provision-master-stack:
    name: Provision master stack
    runs-on: ubuntu-latest
    env:
      BRANCH: master
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CLOSESTWINS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CLOSESTWINS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_CLOSESTWINS_REGION }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pipenv
        run: python -m pip install --upgrade pip wheel pipenv
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - run: npm ci
      - name: Provision PR stack
        uses: dhollerbach/github-action-serverless-with-python-requirements@master
        with:
          args: --stage master
        env:
          AWS_REGION: ${{ secrets.AWS_CLOSESTWINS_REGION }}
          AWS_CLOSESTWINS_ARTIFACTS_BUCKET: ${{ secrets.AWS_CLOSESTWINS_ARTIFACTS_BUCKET }}
          SHARED_API_BRANCH: master
          ENVIRONMENT: prod
          MAP_API_KEY: ${{ secrets.MAP_API_KEY }}
