name: Deploy
on:
  workflow_call:
    inputs:
      branch:
        description: "A branch passed from the caller workflow"
        required: true
        type: string
      environment:
        description: "An environment passed from the caller workflow"
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_region:
        required: true
      artifacts_bucket:
        required: true
      cfn_bucket:
        required: true
      map_api_key:
        required: true

jobs:
  provision-stack:
    name: Provision APP stack
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ inputs.branch }}
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ secrets.aws_region }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pipenv
        run: python -m pip install --upgrade pip wheel pipenv
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - run: npm ci
      - name: Install Serveless
        run: npm install -g serverless
      - name: Deploy
        run: serverless deploy --stage ${{ inputs.environment}}-${{ inputs.branch }}
        env:
          AWS_REGION: ${{ secrets.aws_region }}
          AWS_CLOSESTWINS_ARTIFACTS_BUCKET: ${{ secrets.artifacts_bucket }}
          SHARED_API_BRANCH: master
          ENVIRONMENT: ${{ inputs.environment}}
          MAP_API_KEY: ${{ secrets.map_api_key }}
